export const NEW_MESSAGE = 200

export const NEW_MESSAGE_WITH_INVITE = 2000
export const NEW_MESSAGE_WITH_REMOVE = 2001
export const NEW_MESSAGE_WITH_LEFT = 2002
export const NEW_MESSAGE_WITH_INFO_UPDATE = 2003

export const FETCH_CHAT_SUCCESS = 201
export const SIGN_IN_SUCCESS = 202
export const SIGN_UP_SUCCESS = 203
export const SEND_SUCCESS = 204
export const FETCH_USERS_SUCCESS = 205
export const FETCH_CHATS_SUCCESS = 206
export const FETCH_MESSAGES_SUCCESS = 207
export const SEARCH_USERS_SUCCESS = 208
export const FETCH_ONLINE_USERS_SUCCESS = 209
export const START_TYPING_RESPONSE = 210
export const END_TYPING_RESPONSE = 211
export const DELETE_CHAT_SUCCESS = 212

export const ERROR = 300